module Nirvana {

union BindInfo switch (boolean)
{
	case TRUE: string module_name;
	case FALSE: Object obj;
};

interface SysDomain
{
	void get_bind_info (in string obj_name, in unsigned short platform, out BindInfo bind_info);
	Object get_service (in string id);
};

};
