/// \file File operations.
/*
* Nirvana runtime library.
*
* This is a part of the Nirvana project.
*
* Author: Igor Popov
*
* Copyright (c) 2021 Igor Popov.
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU Lesser General Public License as published by
* the Free Software Foundation; either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU Lesser General Public
* License along with this library.  If not, see <http://www.gnu.org/licenses/>.
*
* Send comments and/or bug reports to:
*  popov.nirvana@gmail.com
*/
#ifndef NIRVANA_FILE_IDL_
#define NIRVANA_FILE_IDL_

#include "CORBA/CosNaming.idl"
#include <CORBA/TimeBase.idl>
#include <CORBA/CosTypedEventChannelAdmin.idl>

typedef unsigned short mode_t;
typedef unsigned long dev_t;
typedef unsigned long nlink_t;
typedef unsigned long blksize_t;
typedef unsigned long long blkcnt_t;

module Nirvana {

typedef unsigned long long ino_t; // TODO: Move out of namespace
typedef unsigned long long FileSize;

/// \brief File status structure (see POSIX struct stat)
///   TimeBase::UtcT::tdf fields are always zero.
///   If TimeBase::UtcT::time field is zero than this
///   file time value is unavailable for a directory item.
struct FileStat
{
	ino_t ino;
	dev_t dev;
	mode_t mode;
	unsigned short type; // See FileType, packed in 2 bytes
	nlink_t nlink;
	FileSize size;
	TimeBase::UtcT
		creation_time,
		last_access_time,
		last_write_time;
	blkcnt_t blkcnt;
	blksize_t blksize;
};

enum FileType
{
	none,
	not_found,
	regular,
	directory,
	symlink,
	block,
	character,
	fifo,
	socket,
	unknown
};

typedef CORBA::OctetSeq DirItemId;

/// \brief Directory item: File or Directory
interface DirItem
{
	/// Item type.
	readonly attribute FileType type;

	/// File status information.
	/// 
	/// \param [out] st FileStat structure.
	void stat (out FileStat st);

	/// \brief Delete all links to a file or empty directory.
	void remove ();

	/// \brief Get unique file system item ID.
	readonly attribute DirItemId id;
};

/// \brief File system locator.
/// 
/// This interface may be obtained as a facet from the SysDomain service.
/// 
interface FSLocator
{
	/// \brief Obtain file system item by the unique DirItemId.
	/// 
	/// \param id File system item ID obtained from DirItem::id attribute.
	/// \returns DirItem object.
	DirItem get_item (in DirItemId id);
};

/// \brief Directory entry (see POSIX struct dirent).
struct DirEntry
{
	FileStat st;
	CosNaming::NameComponent name;
};

typedef sequence <DirEntry> DirEntryList;

/// Implements POSIX DIR* functionality.
interface DirIterator
{
	boolean next_one (out DirEntry de);
	boolean next_n (in unsigned long how_many, out DirEntryList l);
	void destroy ();
};

abstract interface Access;

/// \brief A directory.
interface Dir : DirItem, CosNaming::NamingContext
{
	/// \brief Open or create a file.
	///
	/// \param n File path relative to this directory.
	/// 
	/// \param flags File open flags.
	/// 
	/// \param mode Specifies the file mode bits to be applied when a new file is created.
	///             If neither O_CREAT nor O_TMPFILE is specified in flags, then mode is ignored.
	/// 
	/// \returns File access object.
	/// 
	/// \throws CosNaming::InvalidName
	/// \throws CosNaming::NotFound
	Access open (in CosNaming::Name n, in unsigned short flags, in mode_t mode)
		raises (InvalidName, NotFound);

	/// Generates a unique temporary filename from template, creates and opens the file, and returns
	/// an open file access object for the file.
	/// 
	/// Like Unix mkostemps().
	///
	/// \param [in,out] name Name template of the form prefixXXXXXXsuffix, and the string XXXXXX is replaced
	///                      with a string that makes the filename unique.
	/// 
	/// \param suffix_len Length of the template suffix.
	/// 
	/// \param flags May be zero or include O_DIRECT or O_APPEND flags.
	/// 
	/// \returns File access object.
	Access mkostemps (inout string name, in unsigned short suffix_len, in unsigned short flags);

	/// Skip items that would otherwise result in permission denied errors.
	const unsigned short SKIP_PERMISSION_DENIED = 0x0001;

	/// Ignore case in RegEx expression.
	const unsigned short REGEX_ICASE = 0x0002;

	/// Implements POSIX opendir functionality.
	/// 
	/// \param regexp Regular expression for the item name.
	/// 
	/// \param flags Flags.
	/// 
	/// \param how_many The \p how_many parameter determines the maximum number of entries to return
	///   in the parameter \p dl, with any remaining entries to be accessed through the returned
	///   DirIterator \p di.
	/// 
	/// \param dl The \p dl parameter is a sequence where each element is a DirEntry.
	/// 
	/// \param di The parameter \p di returns a reference to an iterator object.
	/// 
	///   If the \p di parameter returns a non-nil reference, this indicates that the call to opendir()
	///   may not have returned all of the entries and that the remaining entries (if any) must be
	///   retrieved using the iterator. This applies for all values of \p how_many.
	/// 
	void opendir (in string regexp, in unsigned short flags, in unsigned long how_many,
		out DirEntryList dl, out DirIterator di);

	// TODO: Add event source for directory changes.
};

/// \brief A file.
interface File : DirItem
{
	/// \brief File size.
	readonly attribute FileSize size;

	/// \brief Open file access.
	///
	/// \param flags File open flags.
	/// \param mode Specifies the file mode bits to be applied when a new file is created.
	///             If O_CREAT is not specified in flags, then mode is ignored.
	/// \returns File access object.
	Access open (in unsigned short flags, in mode_t mode);
};

/// \brief General file access.
abstract interface Access
{
	/// The File object
	readonly attribute File file;

	/// Close file access
	void close ();

	/// File access flags
	readonly attribute unsigned short flags;

	/// Set file access flags.
	/// 
	/// \param mask The bit mask of the change flags.
	///   If mask bit is 0, the flags bit will remain the same.
	/// 
	/// \param flags The new flags.
	/// 
	void set_flags (in unsigned short mask, in unsigned short flags);

	/// Create independent copy of the file access object.
	/// 
	/// This operation is not used in the POSIX descriptor duplication and works in another way.
	/// Unlike the POSIX `dup()`, new object does not share anything.
	/// Initial object attributes such as flag and position are derived
	/// but can be later changed independently from the original object.
	/// 
	/// \param mask The bit mask of the change flags.
	///   If mask bit is 0, the flags bit will remain the same.
	/// 
	/// \param flags The new flags.
	Access dup (in unsigned short mask, in unsigned short flags);
};

/// Data buffer.
typedef sequence <octet> Bytes;

/// File lock type
enum LockType {
	LOCK_NONE, ///< No lock.
	LOCK_READ, ///< Lock read.
	LOCK_WRITE ///< Lock write.
};

/// File lock parameters.
struct FileLock
{
	FileSize start; ///< Offset where the lock begins.
	FileSize len;   ///< Size of the locked area; zero means until EOF.
	LockType type;  ///< Lock type.
};

/// \brief Direct file access.
interface AccessDirect : Access
{
	/// Read data.
	/// 
	/// \param rel File lock to release.
	/// \param pos Reading position.
	/// \param size The maximum number of bytes to be read.
	/// \param lock Lock type to acquire on the readed data.
	/// \param nonblock Force O_NONBLOCK mode for locking.
	/// \param[out] data Readed data.
	void read (in FileLock rel, in FileSize pos, in unsigned long size, in LockType lock,
		in boolean nonblock, out Bytes data);

	/// Write data
	/// 
	/// \param pos Writing position. If pos == std::numeric_limits <FileSize>::max(),
	///            the data will be appended to the end of file.
	/// \param data Data to write.
	/// \param rel File lock to release.
	/// \param sync Force O_SYNC mode for synchronous write-through.
	void write (in FileSize pos, in Bytes data, in FileLock rel, in boolean sync);

	/// Write dirty blocks to device.
	void flush ();

	/// File size.
	attribute FileSize size;

	/// Change file locking.
	/// 
	/// Atomically releases \p rel locking and acquires \p acq locking.
	/// 
	/// \param rel File lock to release. If rel.type == LOCK_NONE, parameter ignored.
	/// \param acq File lock to acquire. If acq.type == LOCK_NONE, parameter ignored.
	/// \param nonblock Force O_NONBLOCK mode.
	void lock (in FileLock rel, in FileLock acq, in boolean nonblock);

	/// Get file locking.
	/// 
	/// \param fl On input to this call, \p fl describes a lock we would like to place on the file.
	///   If the lock could be placed, get_lock returns LOCK_NONE in the type field of \p fl and
	///   leaves the other fields of the structure unchanged.
	///
	///   If one or more incompatible locks would prevent this lock
	///   being placed, then fcntl () returns details about one of
	///   those locks in the \p fl.
	///
	void get_lock (inout FileLock fl);
};

struct CharFileEvent
{
	string data;
	short error;
};

interface CharFileSink
{
	void received (in CharFileEvent evt);
};

interface PullCharFileSink
{
	void received (out CharFileEvent evt);
	boolean try_received (out CharFileEvent evt);
};

interface CharFileReceiver : CharFileSink, CosTypedEventComm::TypedPushConsumer
{};

/// \brief Character device access.
interface AccessChar : Access
{
	/// Connection point for reading event consumer.
	CosTypedEventChannelAdmin::TypedConsumerAdmin for_consumers ();

	/// Write data
	/// 
	/// \param data Data to write.
	void write (in string data);

	/// \brief Clear reading error.
	/// If device is in read error state, clears the error state and restarts reading.
	/// 
	/// \returns Error code, if any.
	short clear_read_error ();
};

native Pointer; ///< void*
native ConstPointer; ///< const void*
native Size; ///< size_t

/// \brief Buffered file access
valuetype AccessBuf supports Access
{
	Size read (in Pointer p, in Size cb);
	void write (in ConstPointer p, in Size cb);

	ConstPointer get_buffer_read (inout Size cb);
	Pointer get_buffer_write (in unsigned long cb);
	void release_buffer (in unsigned long cb);

	/// File size.
	readonly attribute FileSize size;

	void flush ();

	/// Get/set current file position.
	public FileSize position;

	private AccessDirect access;
	private unsigned long block_size;
	private unsigned short private_flags;
	private char eol [2];
};

};

#endif
