/// \file
/*
* Nirvana runtime library.
*
* This is a part of the Nirvana project.
*
* Author: Igor Popov
*
* Copyright (c) 2021 Igor Popov.
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU Lesser General Public License as published by
* the Free Software Foundation; either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU Lesser General Public
* License along with this library.  If not, see <http://www.gnu.org/licenses/>.
*
* Send comments and/or bug reports to:
*  popov.nirvana@gmail.com
*/
module Nirvana {

native Pointer; ///< void*
native ConstPointer; ///< const void*
native Size; ///< size_t
native UIntPtr; ///< uintptr_t

/// %Memory manager interface.
pseudo interface Memory
{
  /// %Memory must be available for read and write (by default).
  const unsigned short READ_WRITE = 0x0000;

  /// %Memory must be available for read only.
  const unsigned short READ_ONLY = 0x0001;

  /// %Memory must be reserved.
  const unsigned short RESERVED = 0x0002;

  /// %Memory must be initialized by zeroes.
  const unsigned short ZERO_INIT = 0x0040;

  /// The memory must be allocated exactly at the specified address.
  /// If allocation is unavailable, exception must not be thrown.
  const unsigned short EXACTLY = 0x0080;

  /// Special flag for simple memory copy.
  const unsigned short SIMPLE_COPY = 0x0100;

  /** Allocates memory.
    \param [in]       dst Block address to allocate or `nullptr`.
    
    \param [in, out] size Allocation size.
                          Aligned up to the #ALLOCATION_UNIT margin.
    
    \param [in]     flags Allocation flags. This parameter can be one of the following values.

    <table>
    <tr><th>Value</th><th></th>Meaning</tr>
    <tr><td>[#ZERO_INIT] [ | #READ_WRITE] [ | #EXACTLY]</td><td>
      The memory must be committed. If parameter #ZERO_INIT is present, the allocated block is initialized by zeroes.
    </td></tr>
    <tr><td>#RESERVED [ | #READ_WRITE] [ | #EXACTLY]</td><td>
      The memory must be reserved.
    </td></tr>
    <tr><td>#RESERVED | #READ_ONLY [ | #EXACTLY]</td><td>
      The memory must be reserved for read-only access.
    </td></tr>
    </table>
  
    \returns Address of the allocated block.
             The operation may return `nullptr` only if #EXACTLY flag is present.

    The allocated block address and size always aligned on the #ALLOCATION_UNIT.
    If \p size >= #PROTECTION_UNIT, the address is always aligned on the #PROTECTION_UNIT,
    otherwise the entire block will allocated inside the one #PROTECTION_UNIT.
    If \p size >= #SHARING_UNIT, the address is always aligned on the #SHARING_UNIT,
    otherwise the entire block will allocated inside the one #SHARING_UNIT.
    If the #RESERVED flag is not present, the memory block is committed.
    The committed size may be less than allocated size but not less than size parameter.

    If \p dst != nullptr, the memory service tries to allocate memory at that address.
    If #EXACTLY flag is not present and allocation at specified addres is not possible,
    service allocates memory at any other suitable address.
    Impossibility to allocate memory at dst address does not cause an exception.
    The dst value is used by service only as a hint.
    The cause for refuse allocation at the specified address may be also an inappropriate
    alignment.
    If #EXACTLY flag is present and \p dst is not properly aligned, the service tries
    to allocate a larger block aligning the dst down to the desired margin.
    If #EXACTLY flag is specified and memory allocation at dst address is impossible,
    allocate() returns `nullptr`.

    \throws CORBA::NO_MEMORY Not enough memory for allocation.
    \throws CORBA::INV_FLAG  Invalid \p flags parameter value.
    \throws CORBA::BAD_PARAM The \p size parameter is 0.
  */
  Pointer allocate (in Pointer dst, inout Size size, in unsigned short flags);

  /** Makes reserved memory block read-write.
    \param dst  The memory block address.
    \param size The memory block size.

    The memory block must be allocated by this instance of memory management service or an exception will be thrown.
    The block must not contain not allocated memory.
    The real margins of the committed block are extended to the #PROTECTION_UNIT margin.
    If \p size == 0, the operation does nothing.
    The second commit of already committed memory is not an error.

    \throws CORBA::NO_MEMORY Not enough physical memory.
    \throws CORBA::BAD_PARAM The memory block state is not valid.
   */
  void commit (in Pointer dst, in Size size);

  /** Releases the physical memory and makes the memory block reserved.
    \param dst  The memory block address.
    \param size The memory block size.

    The memory block must be allocated by this instance of memory management service or an exception will be thrown.
    The real margins of the committed block are shrinked to the #PROTECTION_UNIT margin.
    If \p size == 0, the operation does nothing.
    The second decommit of already decommitted memory is not an error.

    \throws CORBA::BAD_PARAM The memory block state is not valid.
   */
  void decommit (in Pointer dst, in Size size);
  
  /** Releases the memory block.
    \param dst  The memory block address.
    \param size The memory block size.

    The memory block must be allocated by this instance of memory management service or an exception will be thrown.
    The block must not contain not allocated memory.
    The real margins of the released block are extended to the #ALLOCATION_UNIT margin.
    If \p size == 0, the operation does nothing.

    \throws CORBA::BAD_PARAM The memory block state is not valid.
   */
  void release (in Pointer dst, in Size size);

  /// Allocate destination block
  const unsigned short DST_ALLOCATE = 0x0008;

  /// Decommit source block
  const unsigned short SRC_DECOMMIT = 0x0010;

  /// Release source block
  const unsigned short SRC_RELEASE = 0x0030;

  /** Copies the block of memory.
    \param [in]      dst  Target address.
    \param [in]      src  Source address.
    \param [in, out] size Block size. If \p size == 0 operation does nothing.
    \param [in]     flags Flags. This parameter can contain one or more the following values.

    <table>
    <tr><th>Value</th><th></th>Meaning</tr>
    <tr><td>#READ_ONLY</td><td>
      The copied pages must be available only for read.
    </td></tr>
    <tr><td>#READ_WRITE</td><td>
      The copied pages must be available for write. If #READ_ONLY flag is present,
      #READ_WRITE flag is ignored.
    </td></tr>
    <tr><td>#SRC_DECOMMIT</td><td>
      The source pages must be decommitted but left in the #MEM_RESERVED state.
      The real address and size of the decommitted block are aligned in on the #COMMIT_UNIT margin.
      Works like the decommit() call immediately after copy().
      If flag #SRC_RELEASE is also present, #SRC_DECOMMIT is ignored.
      If source and target blocks overlap, only not overlapped part of the source block is decommitted.
      Source block must be allocated by this instance of the memory service.
    </td></tr>
    <tr><td>#SRC_RELEASE</td><td>
      The source memory block must be released.
      The real address and size of the decommitted block are aligned out on the #ALLOCATION_UNIT margin.
      If source and target blocks overlap, only not overlapped part of the source block is released.
      Source block must be allocated by this instance of the memory service.
    </td></tr>
    <tr><td>#DST_ALLOCATE</td><td>
      A new memory block must be allocated.
      If source and target blocks overlap, the memory service tries to allocate only not averlapped part of
      the target block.
    </td></tr>
    <tr><td>#EXACTLY</td><td>
      If memory allocation at the specified address is not possible, return `nullptr`.
      If flag #DST_ALLOCATE is not specified and \p dst is not `nullptr` this flag is ignored.
    </td></tr>
    <tr><td>#SIMPLE_COPY</td><td>
      Simple copy memory. This flag is incompatible with any other flags except for #READ_WRITE.
      If \p dst is `nullptr` or points to the read-only memory, the exception is thrown.
    </td></tr>
    </table>

    \returns The copied block pointer.
             If #EXACTLY flag is present and new block is allocated, returned value points to allocated block
             and can vary from \p dst due to alignment.

    Source and target blocks may overlap or even be the same.
    Note that flags #DST_ALLOCATE, #SRC_DECOMMIT and #SRC_RELEASE are applied to not overlapped parts only.

    If \p dst == `nullptr` or flag #DST_ALLOCATE is present, new target block is reserved.

    If target block contains pages in states #MEM_READ_ONLY or #MEM_RESERVED, the target block must be
    allocated by this instance of memory service. Otherwise it may be any memory area available for write.

    Te copy() operation may be used for the memory protection change. In this case, when the block is not
    aligned on the #PROTECTION_UNIT margin, for #READ_ONLY it will be aligned in, for #READ_WRITE - aligned out.
    So the service is guaranteed that all read-write memory is available for write, but not guaranteed that all
    read-only memory will be protected for write.

    \throws CORBA::NO_MEMORY     Not enough memory.
    \throws CORBA::INV_FLAG      Invalid \p flags value.
    \throws CORBA::BAD_PARAM     Invalid state of the pages.
    \throws CORBA::NO_PERMISSION Target memory block is not owned by this service instance and is not available for write.
   */
  Pointer copy (in Pointer dst, in Pointer src, inout Size size, in unsigned short flags);

  /** Checks the memory pages for absence of sharing.
    \param p    The memory block pointer.
    \param size The memory block size.
    \returns    `true` if memory is not shared.

    This operation is intended for use in file cashing.
    If the pages are not shared, is_private() returns `true`. If is_private() returned `false` it does not mean
    that pages is still shared. The virtual copies of the page may be released asynchronously, so the page
    sharing may be ended at any moment. So `false` means that some pages in memory range are shared or were
    shared in the past.

    This method always returns `true` for read-only memory because it makes no sense to detect sharing of read-only pages.

    \throws CORBA::BAD_PARAM Invalid state of the memory pages.
   */
  boolean is_private (in ConstPointer p, in Size size);

  /// Implementation parameter for query()
  enum QueryParam
  {
    /** (size_t)query();
      Minimal size of the allocated memory block. Power of 2. All addresses and sizes are aligned on this value.
      In cases when the allocation unit can vary for different block sizes, flags or other circumstances,
      query () must return the minimal value.
     */
    ALLOCATION_UNIT,

    /** (size_t)query();
      The memory blocks with different protection (read-write/read-only) aligned on this boundary. Power of 2.
      Usually equal to the CPU page size.If the implementation does not support memory protection
      0 is returned.
     */
    PROTECTION_UNIT,

    /** (size_t)query();
      Operations commit() and decommit() align the block size on this boundary. Power of 2.
      Usually equal to the CPU page size. If the implementation does not support memory protection
      0 is returned.
     */
    COMMIT_UNIT,
    
    /** (size_t)query();
      >= COMMIT_UNIT. For the some implementations, performing commit()/decommit() with larger block
      let to increase performance.
     */
    OPTIMAL_COMMIT_UNIT,

    /** (size_t)query();
      The minimal size of memory block that may be shared. Usually equal to the CPU page size.
      For Windows equal to 64K.
     */
    SHARING_UNIT,

    /** (size_t)query();
      The memory mapping associativity. A memory block with address p1 may be shared by the block with address p2
      if `p1 % query(p1, SHARING_ASSOCIATIVITY) == p2 % query(p2, SHARING_ASSOCIATIVITY)`. Power of 2.
      `query(p, SHARING_ASSOCIATIVITY) >= query(p, SHARING_UNIT)`. For Windows equal to 64K.
     */
    SHARING_ASSOCIATIVITY,

    /** (size_t)query();
      The memory granularity. The size of memory block over all characterisitics are repeated.
      Equal to maximal value of ALLOCATION_UNIT, PROTECTION_UNIT and SHARING_ASSOCIATIVITY.
     */
    GRANULARITY,

    /** (const void*)query();
      Minimal address of the memory block that can be allocated.
      If p == nullptr, query() returns the minimal memory address that may be allocated in system.
      If p != nullptr, query() returns the address of the beginning of the memory region with all memory parameters equal to
      memory parameters with address p.
     */
    ALLOCATION_SPACE_BEGIN,

    /** (const void*)query();
      Maximal address immediately followed by the end of the allocated memory block.
      If the memory block can be allocated at the end of address space, returned `nullptr`.
      If p != nullptr, query() returns the address immediately following the end of the memory region with all memory parameters equal to
      memory parameters with address p.
     */
    ALLOCATION_SPACE_END,
    
    /** (uint16_t)query();
      \ref memory_flags.
     */
    FLAGS,

    /** (#MemoryState)query();
      The memory state at the specified address.
      p must be != nullptr.
     */
    MEMORY_STATE
  };

  /// The memory block state
  enum MemoryState
  {
    MEM_NOT_ALLOCATED, ///< %Memory is not allocated
    MEM_RESERVED, ///< %Memory block is reserved
    MEM_READ_ONLY, ///< %Memory block is read-only
    MEM_READ_WRITE ///< %Memory block is read-write
  };

  /** Query implementation parameters.
    \param p     %Memory address.
    Implementation parameters can vary for the different memory regions.
    To query the common parameter value use p = `nullptr`.

    \param param The querying parameter.

    \returns The returned value type depens on the requested parameter.
  */
  UIntPtr query (in ConstPointer p, in QueryParam param);

  /** 
   * \defgroup memory_flags Service implementation flags
   * @{
   */

  /// Hardware memory protection present.
  /// 
  /// Service does not require the hardware memory protection support.
  /// Simple embedded systems may not have the hardware memory protection support.
  const unsigned short HARDWARE_PROTECTION = 0x0001;

  /// Copy-On-Write is supported.
  /// 
  /// If this flag is not set, all copy() operationw will cause physical coppying.
  const unsigned short COPY_ON_WRITE = 0x0002;

  /// Address space reservation is supported.
  /// 
  /// If this flag is not set, the RESERVED flag is ignored by the all operations.
  const unsigned short SPACE_RESERVATION = 0x0004;
  
  /// Access check is provided.
  /// 
  /// Simplest system may ignore the memory protection (read-only).
  const unsigned short ACCESS_CHECK = 0x0008;
  
  /**@}*/
};

};
