/// \file
/// National Languages Support
/*
* Nirvana runtime library.
*
* This is a part of the Nirvana project.
*
* Author: Igor Popov
*
* Copyright (c) 2021 Igor Popov.
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU Lesser General Public License as published by
* the Free Software Foundation; either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU Lesser General Public
* License along with this library.  If not, see <http://www.gnu.org/licenses/>.
*
* Send comments and/or bug reports to:
*  popov.nirvana@gmail.com
*/
module Nirvana {

/// A NLS code page.
/// 
/// Only single-byte code pages are supported.
valuetype CodePage
{
	/// Convert narrow character to wide character.
	/// 
	/// \param narrow A narrow character.
	/// \returns Wide character.
	unsigned long to_wide (in octet narrow);

	/// Convert wide character to narrow character.
	/// 
	/// \param wide A wide character.
	/// \param default_char Character to use if a character cannot be represented in the specified
	///   code page. If \p default_char > 0x7F and a character cannot be represented in the specified
	///   code page, CORBA::CODESET_INCOMPATIBLE exception will be thrown.
	/// \param [out] used_default If default character is specified and was used,
	///   \p used_default set to `true`.
	/// \returns Narrow character.
	octet to_narrow (in unsigned long wide, in octet default_char, out boolean used_default);

	/// Do not use default character.
	const octet NO_DEFAULT = 0xFF;

	/// Standard OSF code page id.
	/// 
	/// See OSF Character and Code Set Registry, OSF DCE FRC 40.1
	/// Also: ftp://ftp.opengroup.org:/pub/code_set_registry
	readonly attribute unsigned long id;

	/// Create the code page.
	/// 
	/// \param id The code page id.
	factory create (in unsigned long id);
};

};
