/// \file
/*
* Nirvana runtime library.
*
* This is a part of the Nirvana project.
*
* Author: Igor Popov
*
* Copyright (c) 2021 Igor Popov.
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU Lesser General Public License as published by
* the Free Software Foundation; either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU Lesser General Public
* License along with this library.  If not, see <http://www.gnu.org/licenses/>.
*
* Send comments and/or bug reports to:
*  popov.nirvana@gmail.com
*/
#ifndef NIRVANA_SHELL_IDL_
#define NIRVANA_SHELL_IDL_

#include "File.idl"

module Nirvana {

struct FileDescr
{
	Access access;
	sequence <unsigned short> descriptors;
};

typedef sequence <FileDescr> FileDescriptors;

interface Process
{
	readonly attribute boolean completed;
	readonly attribute long exit_code;
	void wait ();
	boolean kill ();
};

interface ProcessCallback
{
	oneway void on_process_finish (in Process process);
};

typedef sequence <string> StringSeq;

local interface Cmdlet
{
	short run (in StringSeq argv);
};

/// Shell helper.
interface Shell
{
	/// Spawn process.
	/// 
	/// \param file The process binary module.
	/// \param argv The arguments.
	/// \param envp The environment variables.
	/// \param work_dir The working directory (can be empty string).
	/// \param files File descriptors to inherit.
	/// \param callback The process termination callback.
	/// \returns Process object.
	Process spawn (in AccessDirect file, in StringSeq argv, in StringSeq envp, in string work_dir,
		in FileDescriptors files, in ProcessCallback callback);

	short run_cmdlet (in string name, in StringSeq argv, in StringSeq envp, in string work_dir,
		in FileDescriptors files);

	void create_pipe (out AccessChar pipe_out, out AccessChar pipe_in);
};

const Shell the_shell;

};

#endif
