/// \file
/*
* Nirvana runtime library.
*
* This is a part of the Nirvana project.
*
* Author: Igor Popov
*
* Copyright (c) 2021 Igor Popov.
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU Lesser General Public License as published by
* the Free Software Foundation; either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU Lesser General Public
* License along with this library.  If not, see <http://www.gnu.org/licenses/>.
*
* Send comments and/or bug reports to:
*  popov.nirvana@gmail.com
*/
#ifndef NIRVANA_SHELL_IDL_
#define NIRVANA_SHELL_IDL_

#include "File.idl"
#include "BindError.idl"

module Nirvana {

native Int;

struct SpawnFD
{
	FileSize pos;
	Access access;
	sequence <long> descriptors;
};

struct SpawnFiles
{
	sequence <SpawnFD> files;
	string work_dir;
};

typedef sequence <string> StringSeq;

pseudo interface Cmdlet
{
	Int run (in StringSeq argv);
};

/// Shell helper.
pseudo interface Shell
{
	/// \brief Get current spawn files information.
	/// 
	/// \returns FileDescriptors
	void get_spawn_files (out SpawnFiles files);

	/// \brief Obtain platform identifier for a binary file.
	/// 
	/// \param binary Binary file access.
	/// \returns Platform id.
	PlatformId get_binary_platform (in AccessDirect binary);

	/// \brief Run Cmdlet.
	/// 
	/// \param argv The arguments. First argument is CmdLet name.
	/// \param files Spawn files context. Use get_spawn_files() to obtain it.
	/// \returns Cmdlet exit code.
	Int cmdlet (in StringSeq argv, in SpawnFiles files) raises (BindError::Error);

	/// \brief Run process.
	/// 
	/// \param argv The arguments. First argument is process executable file.
	/// \param files Spawn files context. Use get_spawn_files() to obtain it.
	/// \returns Process exit code.
	Int spawn (in StringSeq argv, in SpawnFiles files) raises (BindError::Error);

	void create_pipe (out AccessChar pipe_out, out AccessChar pipe_in);
};

const Shell the_shell;

};

#endif
